version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MONGODB_URI: mongodb://db:27017/compacine
  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: